baseURL = 'https://lexp.lt'
languageCode = 'en-us'
pagination.pagerSize = 10
title = 'Lexy Plt blog'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'en'

enableGitInfo = true
enableRobotsTXT = true

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

